name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        type: string
      release_name:
        description: 'Release name'
        required: true
        type: string
        default: ''

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v6
        with:
          persist-credentials: false

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Extract .7z files
        run: |
          for file in *.7z.001*; do
            if [ -f "$file" ]; then
              7z x "$file" -aoa
            fi
          done

      - name: Generate SHA256 checksums
        run: |
          for file in ./_*.txt;
          do
            if [ -f "$file" ]; then
              sha256sum "$file" > "$file.sha256";
              echo "Generated checksum for $file";
            fi
          done

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.event.inputs.tag_name }}" \
            _*.txt \
            --title "${{ github.event.inputs.release_name || github.event.inputs.tag_name }}" \
            --generate-notes
